import type { Sprite } from "../sprite";

// Opponent, Guard player: hair pulled back into a top knot with a blue band, a relaxed grin, a
// white gi with a blue sponsor patch on each side of the chest, today's belt (L). Faces right. 32x40.
export const guardPlayer: Sprite = {
  rows: [
    "..........kkk...................",
    ".........khhhk..................",
    ".........khhhkkkkkkkk...........",
    ".........kBBBkkhhhhhhhk.........",
    "........khhhhhhhhhhhhhhk........",
    ".......khhhhhhhhhhhhhhhk........",
    ".......khhhhhhhhhhhhhhhk........",
    ".......khhhhhhhhsssssssk........",
    ".......khhhhhhsssssssssk........",
    ".......khhsssssssssssssk........",
    ".......khhhssssssshhhssk........",
    ".......khssssssssswkssk.........",
    ".......khSSssssssswkssk.........",
    ".......khSSssssssssssssk........",
    ".......kkSsssssssssssssk........",
    "........kSsssssssskwwksk........",
    "........kSSsssssssskksk.........",
    ".........kSSsssssssssk..........",
    "..........kSSSssssskk...........",
    "...........kkSSsssk.............",
    ".........kkkwkSssskwkkk.........",
    ".......kkwwwwkkSskkwwwwkk.......",
    ".....kkwwwwwwwkSsskwwwwwwkk.....",
    "....kwwwwwwwwwgkSskgwwwwwwwk....",
    "...kwwwwwwwwwwwgkskgwwwwwwwwk...",
    "...kwwgwwBBBwwwwgkkgwBBBwwgwk...",
    "..kwwwgwwBBBwwwwwgkwwBBBwwgwwk..",
    "..kwwwgkwwwwwwwwwwgkwwwwwkgwwk..",
    "..kwwwgkwwwwwwwwwwwgwwwwwkgwwk..",
    "..kwwwgkwwwwwwwwwwwgwwwwwkgwwk..",
    "..kwwgkkwwwwwwwwwwwgwwwwwkkgwk..",
    "..kwwgkwwwwwwwwwwwwgwwwwwwkgwk..",
    "..kssskwwwwwwwwwwwwgwwwwwwksssk.",
    "..kSsskkkkkkkkkkkkkkkkkkkkksssk.",
    "..kSsskLLLLLLLLLLLLLLLLLLkkSsk..",
    "...kSskLLLLLLLLLLLLLLLLLLksSk...",
    "....kkkkkkkkkkkkLLkkkkkkkkkk....",
    "......kwwwwwwwkLkkLkwwwwwwk.....",
    "......kwwwwwwwkLk.kLkwwwwwk.....",
    "......kkkkkkkkkkk..kkkkkkkk.....",
  ],
};
