import type { Sprite } from "../sprite";

// Your fighter, the underdog: spiky dark hair, red headband with its tails flying, white gi, today's
// belt (L). Faces right, toward the opponent. 32x40, head and torso to just below the belt.
export const hero: Sprite = {
  rows: [
    "................................",
    "...........k...k..k.............",
    "..........khk.khkkhk............",
    ".........khhhkhhhhhhk...........",
    "........khhhhhhhhhhhhk..........",
    ".......khhhhhhhhhhhhhhk.........",
    ".......khhhhhhhhhhhhhhhk........",
    "..kk..kRRRRRRRRRRRRRRRRk........",
    ".kRqk.kqqqqqqqqqqqqqqqqk........",
    "kRqk.kkhhsssssssssssssk.........",
    "kqk.kRkhhsshhhsssshhhssk........",
    ".k..kqkhsssssssssswkssk.........",
    "....kk.khSSssssssswkssk.........",
    ".......khSSssssssssssssk........",
    ".......kkSsssssssssssssk........",
    "........kSsssssssssskksk........",
    "........kSSsssssssssssk.........",
    ".........kSSsssssssssk..........",
    "..........kSSSssssskk...........",
    "...........kkSSsssk.............",
    ".........kkkwkSssskwkkk.........",
    ".......kkwwwwkkSskkwwwwkk.......",
    ".....kkwwwwwwwkSsskwwwwwwkk.....",
    "....kwwwwwwwwwgkSskgwwwwwwwk....",
    "...kwwwwwwwwwwwgkskgwwwwwwwwk...",
    "...kwwgwwwwwwwwwgkkgwwwwwwgwk...",
    "..kwwwgwwwwwwwwwwgkwwwwwwwgwwk..",
    "..kwwwgkwwwwwwwwwwgkwwwwwkgwwk..",
    "..kwwwgkwwwwwwwwwwwgwwwwwkgwwk..",
    "..kwwwgkwwwwwwwwwwwgwwwwwkgwwk..",
    "..kwwgkkwwwwwwwwwwwgwwwwwkkgwk..",
    "..kwwgkwwwwwwwwwwwwgwwwwwwkgwk..",
    "..kssskwwwwwwwwwwwwgwwwwwwksssk.",
    "..kSsskkkkkkkkkkkkkkkkkkkkksssk.",
    "..kSsskLLLLLLLLLLLLLLLLLLkkSsk..",
    "...kSskLLLLLLLLLLLLLLLLLLksSk...",
    "....kkkkkkkkkkkkLLkkkkkkkkkk....",
    "......kwwwwwwwkLkkLkwwwwwwk.....",
    "......kwwwwwwwkLk.kLkwwwwwk.....",
    "......kkkkkkkkkkk..kkkkkkkk.....",
  ],
};
