import type { Sprite } from "../sprite";

// Opponent, Judo black belt: neat side-parted black hair, one heavy straight brow, a stern flat
// mouth, tan skin, a white judo gi with a thick collar, today's belt (L). Faces right. 32x40.
export const judoka: Sprite = {
  rows: [
    "................................",
    "................................",
    "..........kkkkkkkkkkk...........",
    "........kkhhhhhhhhhhhkk.........",
    ".......khhhhhhhhhhhhhhhk........",
    ".......khhhhhhhhhhhhhhhk........",
    ".......khhhhhhhhhhhhGhhk........",
    ".......khhhhhhhhhhhhhhhk........",
    ".......khhhhhhtttttttttk........",
    ".......khhhhttttttttttk.........",
    ".......khhhtttttthhhhhtk........",
    ".......khhttttttttwkttk.........",
    ".......khTTtttttttwkttk.........",
    ".......kTTtttttttttttttk........",
    ".......kkTtttttttttttttk........",
    "........kTtttttttttkkktk........",
    "........kTTtttttttttttk.........",
    ".........kTTtttttttttk..........",
    "..........kTTTtttttkk...........",
    "...........kkTTtttk.............",
    ".........kkkwkTtttkwkkk.........",
    ".......kkwwwwkkTtkkwwwwkk.......",
    ".....kkwwwwwwwkTttkwwwwwwkk.....",
    "....kwwwwwwwwgGkTtkGgwwwwwwk....",
    "...kwwwwwwwwwwgGktkGgwwwwwwwk...",
    "...kwwgwwwwwwwwwGkkGgwwwwwgwk...",
    "..kwwwgwwwwwwwwwwGkwwwwwwwgwwk..",
    "..kwwwgkwwwwwwwwwwGkwwwwwkgwwk..",
    "..kwwwgkwwwwwwwwwwwGgwwwwkgwwk..",
    "..kwwwgkwwwwwwwwwwwGgwwwwkgwwk..",
    "..kwwgkkwwwwwwwwwwwGgwwwwkkgwk..",
    "..kwwgkwwwwwwwwwwwwGgwwwwwkgwk..",
    "..ktttkwwwwwwwwwwwwgwwwwwwktttk.",
    "..kTttkkkkkkkkkkkkkkkkkkkkktttk.",
    "..kTttkLLLLLLLLLLLLLLLLLLkkTtk..",
    "...kTtkLLLLLLLLLLLLLLLLLLktTk...",
    "....kkkkkkkkkkkkLLkkkkkkkkkk....",
    "......kwwwwwwwkLkkLkwwwwwwk.....",
    "......kwwwwwwwkLk.kLkwwwwwk.....",
    "......kkkkkkkkkkk..kkkkkkkk.....",
  ],
};
