import type { Sprite } from "../sprite";

// Opponent, Leg-lock specialist: shaved head with a shine, a full ginger beard, a sly squint, a
// black gi, today's belt (L). Faces right. 32x40.
export const legLocker: Sprite = {
  rows: [
    "................................",
    "................................",
    "..........kkkkkkkkkk............",
    "........kkssssssssssk...........",
    ".......ksswwsssssssssk..........",
    ".......kswssssssssssssk.........",
    ".......kssssssssssssssk.........",
    ".......kSsssssssssssssk.........",
    ".......kSsssssssssssssk.........",
    ".......kSssssssssrrrrsk.........",
    ".......kSSsssssssskkssk.........",
    ".......kSSsssssssssssssk........",
    ".......kSsssssssssssssk.........",
    ".......kSssrrrrrrrrrrrrk........",
    "........kSrrrrrrrrrrrrrk........",
    "........krrrrrrrrrkkkrrk........",
    "........krrrrrrrrrrrrrk.........",
    ".........krrrrrrrrrrrk..........",
    "..........krrrrrrrrk............",
    "...........kkrrrrrk.............",
    ".........kkkGkSssskGkkk.........",
    ".......kkGGGGkkSskkGGGGkk.......",
    ".....kkGGGGGGGkSsskGGGGGGkk.....",
    "....kGGGGGGGGGhkSskhGGGGGGGk....",
    "...kGGGGGGGGGGGhkskhGGGGGGGGk...",
    "...kGGhGGGGGGGGGhkkhGGGGGGhGk...",
    "..kGGGhGGGGGGGGGGhkGGGGGGGhGGk..",
    "..kGGGhkGGGGGGGGGGhkGGGGGkhGGk..",
    "..kGGGhkGGGGGGGGGGGhGGGGGkhGGk..",
    "..kGGGhkGGGGGGGGGGGhGGGGGkhGGk..",
    "..kGGhkkGGGGGGGGGGGhGGGGGkkhGk..",
    "..kGGhkGGGGGGGGGGGGhGGGGGGkhGk..",
    "..kssskGGGGGGGGGGGGhGGGGGGksssk.",
    "..kSsskkkkkkkkkkkkkkkkkkkkksssk.",
    "..kSsskLLLLLLLLLLLLLLLLLLkkSsk..",
    "...kSskLLLLLLLLLLLLLLLLLLksSk...",
    "....kkkkkkkkkkkkLLkkkkkkkkkk....",
    "......kGGGGGGGkLkkLkGGGGGGk.....",
    "......kGGGGGGGkLk.kLkGGGGGk.....",
    "......kkkkkkkkkkk..kkkkkkkk.....",
  ],
};
