import type { Sprite } from "../sprite";

// Opponent, Scrambler: an orange mohawk running front to back over cropped dark sides, a toothy grin, dark skin, a blue gi
// with the sleeves rolled up, today's belt (L). Faces right. 32x40.
export const scrambler: Sprite = {
  rows: [
    "..........kkk...................",
    ".........kooYk..................",
    "........koooYkk.................",
    "........kooooYokk...............",
    ".......kkoooooooookk............",
    ".......khkkoooooooookk..........",
    ".......khhhkkkkkkkkkhhk.........",
    ".......khhhhhhhhhhhhhhk.........",
    ".......khhhdddddddddddk.........",
    ".......khhdddddddddddddk........",
    ".......khhdddddddhhhddk.........",
    ".......kDdddddddddwkddk.........",
    ".......kDDDdddddddwkddk.........",
    ".......kDDDddddddddddddk........",
    ".......kkDdddddddddddddk........",
    "........kDdddddddkwwwkdk........",
    "........kDDdddddddkkkdk.........",
    ".........kDDdddddddddk..........",
    "..........kDDDdddddkk...........",
    "...........kkDDdddk.............",
    ".........kkkBkDdddkBkkk.........",
    ".......kkBBBBkkDdkkBBBBkk.......",
    ".....kkBBBBBBBkDddkBBBBBBkk.....",
    "....kBBBBBBBBBbkDdkbBBBBBBBk....",
    "...kBBBBBBBBBBBbkdkbBBBBBBBBk...",
    "...kBBbBBBBBBBBBbkkbBBBBBBbBk...",
    "..kBBBbBBBBBBBBBBbkBBBBBBBbBBk..",
    "..kdddDkBBBBBBBBBBbkBBBBBkDddk..",
    "..kdddDkBBBBBBBBBBBbBBBBBkDddk..",
    "..kdddDkBBBBBBBBBBBbBBBBBkDddk..",
    "..kddDkkBBBBBBBBBBBbBBBBBkkDdk..",
    "..kddDkBBBBBBBBBBBBbBBBBBBkDdk..",
    "..kdddkBBBBBBBBBBBBbBBBBBBkdddk.",
    "..kDddkkkkkkkkkkkkkkkkkkkkkdddk.",
    "..kDddkLLLLLLLLLLLLLLLLLLkkDdk..",
    "...kDdkLLLLLLLLLLLLLLLLLLkdDk...",
    "....kkkkkkkkkkkkLLkkkkkkkkkk....",
    "......kBBBBBBBkLkkLkBBBBBBk.....",
    "......kBBBBBBBkLk.kLkBBBBBk.....",
    "......kkkkkkkkkkk..kkkkkkkk.....",
  ],
};
