import type { Sprite } from "../sprite";

// Opponent, Scrambler: an orange mohawk over cropped dark sides, a toothy grin, dark skin, a blue gi
// with the sleeves rolled up, today's belt (L). Faces right. 32x40.
export const scrambler: Sprite = {
  rows: [
    "............k.k.k.k.............",
    "............kokokok.............",
    "............koYoook.............",
    "...........kooYooook............",
    "........kkkkoYoooookkk..........",
    ".......khhhkoYoooookhk..........",
    ".......khhhhkoooooookhk.........",
    ".......khhhhhkkkkkkkhhk.........",
    ".......khhhdddddddddddk.........",
    ".......khhdddddddddddddk........",
    ".......khhdddddddhhhddk.........",
    ".......kDdddddddddwkddk.........",
    ".......kDDDdddddddwkddk.........",
    ".......kDDDddddddddddddk........",
    ".......kkDdddddddddddddk........",
    "........kDdddddddkwwwkdk........",
    "........kDDdddddddkkkdk.........",
    ".........kDDdddddddddk..........",
    "..........kDDDdddddkk...........",
    "...........kkDDdddk.............",
    ".........kkkBkDdddkBkkk.........",
    ".......kkBBBBkkDdkkBBBBkk.......",
    ".....kkBBBBBBBkDddkBBBBBBkk.....",
    "....kBBBBBBBBBbkDdkbBBBBBBBk....",
    "...kBBBBBBBBBBBbkdkbBBBBBBBBk...",
    "...kBBbBBBBBBBBBbkkbBBBBBBbBk...",
    "..kBBBbBBBBBBBBBBbkBBBBBBBbBBk..",
    "..kdddDkBBBBBBBBBBbkBBBBBkDddk..",
    "..kdddDkBBBBBBBBBBBbBBBBBkDddk..",
    "..kdddDkBBBBBBBBBBBbBBBBBkDddk..",
    "..kddDkkBBBBBBBBBBBbBBBBBkkDdk..",
    "..kddDkBBBBBBBBBBBBbBBBBBBkDdk..",
    "..kdddkBBBBBBBBBBBBbBBBBBBkdddk.",
    "..kDddkkkkkkkkkkkkkkkkkkkkkdddk.",
    "..kDddkLLLLLLLLLLLLLLLLLLkkDdk..",
    "...kDdkLLLLLLLLLLLLLLLLLLkdDk...",
    "....kkkkkkkkkkkkLLkkkkkkkkkk....",
    "......kBBBBBBBkLkkLkBBBBBBk.....",
    "......kBBBBBBBkLk.kLkBBBBBk.....",
    "......kkkkkkkkkkk..kkkkkkkk.....",
  ],
};
