import type { Sprite } from "../sprite";

// Opponent, Ex-D1 wrestler: blond buzz cut, grey headgear with a round ear cup, a
// neck as wide as his jaw, broad shoulders, blue gi, today's belt (L). Faces right like every
// portrait; the VS screen mirrors the opponent. 32x40.
export const wrestler: Sprite = {
  rows: [
    "................................",
    "................................",
    "..........kkkkkkkkkkk...........",
    ".........kyyyyyyyyyyyk..........",
    "........kGGGGGGGGGGGGGk.........",
    "........kGgggggggggggGk.........",
    "........kykGGkyyyyyyyyk.........",
    "........kykGGkssssssssk.........",
    ".......kkkGGkkssssssssk.........",
    "......kGGGGGGksshhhsshhk........",
    "......kGgggGGksssssskwssk.......",
    "......kGgGGGGkssssssskwsk.......",
    "......kGgGGGGksssssssssssk......",
    "......kGGGGGGkSsssssssssk.......",
    ".......kGGGGkkSsssssssssk.......",
    "........kkGkSSsssssskkksk.......",
    "..........kSSSsssssssssk........",
    "..........kSSSssssssssk.........",
    "..........kSSSSsssssssk.........",
    ".......kkkkSSSSssssssskkkk......",
    ".....kkbBBBkSSSsssssskBBBBkk....",
    "...kkBBBBBBBkSSssssskBBBBBBBkk..",
    "..kBBBBBBBBBbkSSsssskbBBBBBBBBk.",
    ".kBBBBBBBBBBBbkSsssskbBBBBBBBBBk",
    ".kBBbBBBBBBBBBbkSsskbBBBBBBBbBBk",
    ".kBBbBBBBBBBBBBbkskbBBBBBBBBbBBk",
    ".kBBbkBBBBBBBBBBbkbBBBBBBBkbBBBk",
    ".kBBbkBBBBBBBBBBBbBBBBBBBBkbBBBk",
    ".kBBbkBBBBBBBBBBBbBBBBBBBBkbBBBk",
    ".kBBbkBBBBBBBBBBBbBBBBBBBBkbBBBk",
    ".kBbkkBBBBBBBBBBBbBBBBBBBBkkbBBk",
    ".kBbkBBBBBBBBBBBBbBBBBBBBBBkbBBk",
    ".ksssskBBBBBBBBBbBBBBBBBBBkssssk",
    ".kSssskkkkkkkkkkkkkkkkkkkkkssssk",
    ".kSssskLLLLLLLLLLLLLLLLLLLkkSsk.",
    "..kSsskLLLLLLLLLLLLLLLLLLLksSk..",
    "...kkkkkkkkkkkkkLLkkkkkkkkkkk...",
    ".....kBBBBBBBBkLkkLkBBBBBBBBk...",
    ".....kBBBBBBBBkLk.kLkBBBBBBBk...",
    ".....kkkkkkkkkkk..kkkkkkkkkkk...",
  ],
};
