// Step 5's quality gate: `npx tsx scripts/quality.ts [puzzles]` generates puzzles from the public
// `dev` salt, solves them, and writes docs/guard/QUALITY.md with the numbers.
import { writeFileSync } from "node:fs";

import { compileBoard, finishChance } from "../src/games/guard/engine";
import {
  GATE,
  baseOf,
  measure,
  statShares,
  summarize,
  type PuzzleQuality,
} from "../src/games/guard/quality";
import { guard } from "../src/games/guard/module";
import { STATS, STAT_NAMES } from "../src/games/guard/model";
import { solveCamp } from "../src/games/guard/solver";
import { DEV_SALT, rngFor } from "../src/kit/seed";

const count = Number(process.argv[2] ?? 60);
const rows: string[] = [];
const measured: PuzzleQuality[] = [];
let solveMs = 0;
let evaluations = 0;

for (let n = 1; n <= count; n++) {
  const puzzle = guard.generator.generate(await rngFor(DEV_SALT, "guard", n));
  const t0 = performance.now();
  const solved = solveCamp(compileBoard(puzzle.belt), baseOf(puzzle), puzzle.sessions);
  solveMs += performance.now() - t0;
  evaluations += solved.evaluated;
  const q = measure({
    puzzle,
    optimum: { score: solved.score, solutions: solved.camps.map((camp) => ({ camp })) },
  });
  measured.push({ ...q, optimalCamps: solved.ties });
  const best = solved.camps[0] ?? [];
  const campText = best
    .map((k, i) => (k ? `${STAT_NAMES[STATS[i]!]} ${k}` : ""))
    .filter(Boolean)
    .join(", ");
  rows.push(
    `| ${n} | ${puzzle.card.title} | ${puzzle.fighter.title} | ${puzzle.start} | ${puzzle.exchanges} | ` +
      `${q.baseline / 10}% | ${q.optimum / 10}% | ${q.greedy / 10}% | ${q.randomMean / 10}% | ${solved.ties} | ${campText} |`,
  );
  process.stdout.write(".");
}

// Engine time per camp: what the Worker spends re-scoring one submission.
const sample = guard.generator.generate(await rngFor(DEV_SALT, "guard", 1));
const board = compileBoard(sample.belt);
const t1 = performance.now();
const runs = 200;
for (let k = 0; k < runs; k++) finishChance(board, baseOf(sample));
const engineMs = (performance.now() - t1) / runs;

const m = summarize(measured);
const humanGap = Math.min(m.medianStrengthsGap!, m.medianWeaknessesGap!, m.medianCardGap!);
const shares = statShares(measured);
const top = shares[0];
const topName = top ? STAT_NAMES[STATS[top.stat]!] : "none";
// C(sessions + stats - 1, stats - 1): every way to spread the sessions.
const choose = (n: number, k: number): number => (k === 0 ? 1 : (choose(n - 1, k - 1) * n) / k);
const allCampsCount = Math.round(choose(6 + STATS.length - 1, STATS.length - 1));
const pct = (x: number) => `${(x / 10).toFixed(1)}%`;
// A difference between two chances is in percentage points, not percent.
const pts = (x: number) => `${(x / 10).toFixed(1)} points`;
const gate = [
  [
    `the closest strategy a person would try lands ${pts(humanGap)} below the best (median)`,
    humanGap >= GATE.minHumanGap,
    `at least ${pts(GATE.minHumanGap)}`,
  ],
  [
    `median lift ${pts(m.medianLift!)}`,
    m.medianLift! >= GATE.minMedianLift,
    `at least ${pts(GATE.minMedianLift)}`,
  ],
  [
    `${topName} is in ${Math.round((top?.share ?? 0) * 100)}% of best camps, the most of any stat`,
    (top?.share ?? 0) <= GATE.maxStatShare,
    `at most ${GATE.maxStatShare * 100}%`,
  ],
] as const;

writeFileSync(
  new URL("../docs/guard/QUALITY.md", import.meta.url),
  [
    "# Guard to Sub: quality report",
    "",
    `<!-- Generated by \`npx tsx scripts/quality.ts ${count}\` on the public dev salt. Don't edit by hand. -->`,
    "",
    `${count} puzzles, 6 sessions each. The gate (docs/steps/guard.md, step 5):`,
    "",
    ...gate.map(([what, ok, need]) => `- ${ok ? "✅" : "❌"} ${what} (needs ${need})`),
    "",
    "| Metric | Value |",
    "|---|---|",
    `| Median start (no camp) | ${pct(m.medianBaseline!)} |`,
    `| Median best camp | ${pct(m.medianOptimum!)} (range ${pct(m.minOptimum!)} to ${pct(m.maxOptimum!)}) |`,
    `| Median lift (best minus start) | ${pts(m.medianLift!)} (smallest ${pts(m.minLift!)}) |`,
    `| Greedy finds the best | ${(m.greedyOptimalShare! * 100).toFixed(0)}% of puzzles; median gap ${pts(m.medianGreedyGap!)} |`,
    `| A random camp | median ${pts(m.medianRandomGap!)} below the best |`,
    `| What a person might try | your best stats ${pts(m.medianStrengthsGap!)} below the best; your worst ${pts(m.medianWeaknessesGap!)}; the card's stats ${pts(m.medianCardGap!)} (medians) |`,
    `| Camps tied for best | median ${m.medianOptimalCamps} |`,
    `| Stats a best camp uses | ${m.meanStatsPerCamp!.toFixed(1)} on average |`,
    `| Rejected by the per-puzzle check | ${Math.round(m.rejectedShare! * count)} of ${count} (start not below 50%, lift under 5 points, or best above 95%) |`,
    `| Most-used stats in best camps | ${shares
      .slice(0, 5)
      .map(({ stat, share }) => `${STAT_NAMES[STATS[stat]!]} ${Math.round(share * 100)}%`)
      .join(", ")} |`,
    `| Solver | ${(solveMs / count / 1000).toFixed(2)} s per puzzle, ${Math.round(evaluations / count)} exact evaluations (of ${allCampsCount.toLocaleString("en")} camps) |`,
    `| Engine, one camp | ${engineMs.toFixed(2)} ms (the Worker allows 10 ms of CPU per request) |`,
    "",
    "| # | Opponent | Your fighter | Start | Exchanges | Start % | Best | Greedy | Random | Ties | A best camp |",
    "|---|---|---|---|---|---|---|---|---|---|---|",
    ...rows,
    "",
  ].join("\n"),
);
console.log(
  `\nwrote docs/guard/QUALITY.md: ${JSON.stringify(m)}\nsolve ${(solveMs / count / 1000).toFixed(2)} s/puzzle, engine ${engineMs.toFixed(2)} ms/camp`,
);
for (const [what, ok] of gate) console.log(`${ok ? "PASS" : "FAIL"} ${what}`);
