/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as GGameRouteImport } from './routes/g.$game'
import { Route as LabFightRouteImport } from './routes/lab.fight'
import { Route as LabPlanRouteImport } from './routes/lab.plan'
import { Route as LabReadRouteImport } from './routes/lab.read'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const GGameRoute = GGameRouteImport.update({
  id: '/g/$game',
  path: '/g/$game',
  getParentRoute: () => rootRouteImport,
} as any)
const LabFightRoute = LabFightRouteImport.update({
  id: '/lab/fight',
  path: '/lab/fight',
  getParentRoute: () => rootRouteImport,
} as any)
const LabPlanRoute = LabPlanRouteImport.update({
  id: '/lab/plan',
  path: '/lab/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LabReadRoute = LabReadRouteImport.update({
  id: '/lab/read',
  path: '/lab/read',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/g/$game': typeof GGameRoute
  '/lab/fight': typeof LabFightRoute
  '/lab/plan': typeof LabPlanRoute
  '/lab/read': typeof LabReadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/g/$game': typeof GGameRoute
  '/lab/fight': typeof LabFightRoute
  '/lab/plan': typeof LabPlanRoute
  '/lab/read': typeof LabReadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/g/$game': typeof GGameRoute
  '/lab/fight': typeof LabFightRoute
  '/lab/plan': typeof LabPlanRoute
  '/lab/read': typeof LabReadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/demo' | '/g/$game' | '/lab/fight' | '/lab/plan' | '/lab/read'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo' | '/g/$game' | '/lab/fight' | '/lab/plan' | '/lab/read'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/g/$game'
    | '/lab/fight'
    | '/lab/plan'
    | '/lab/read'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  GGameRoute: typeof GGameRoute
  LabFightRoute: typeof LabFightRoute
  LabPlanRoute: typeof LabPlanRoute
  LabReadRoute: typeof LabReadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$game': {
      id: '/g/$game'
      path: '/g/$game'
      fullPath: '/g/$game'
      preLoaderRoute: typeof GGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/fight': {
      id: '/lab/fight'
      path: '/lab/fight'
      fullPath: '/lab/fight'
      preLoaderRoute: typeof LabFightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/plan': {
      id: '/lab/plan'
      path: '/lab/plan'
      fullPath: '/lab/plan'
      preLoaderRoute: typeof LabPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/read': {
      id: '/lab/read'
      path: '/lab/read'
      fullPath: '/lab/read'
      preLoaderRoute: typeof LabReadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  GGameRoute: GGameRoute,
  LabFightRoute: LabFightRoute,
  LabPlanRoute: LabPlanRoute,
  LabReadRoute: LabReadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
